---
apiVersion: v1
kind: Template
labels:
  app: cockpit-cloud
  template: cockpit-cloud
metadata:
  annotations:
    description: Backend service for cockpit-cloud in console.redhat.com
  name: cockpit-cloud
objects:

- kind: Secret
  apiVersion: v1
  metadata:
    name: cockpit-cloud-pod-keys
    namespace: ephemeral-zmshb3
  data:
    server.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1DNENBUUF3QlFZREsyVndCQ0lFSUVBTTV5OFVpVGZ1S0d3ZEs4UnB2Sm5ldS9NKzRjTEkwRy9VMEpSTG5odGwKLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
    server.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJnVENDQVRPZ0F3SUJBZ0lVSHMvd2RpL3dBeSt2cHdGcE5XVDIrRHhyeEFNd0JRWURLMlZ3TURZeE5EQXkKQmdOVkJBTU1LeW91WVhCd2N5NWpMWEpvTFdNdFpYQm9Mamh3TUdNdWNERXViM0JsYm5Ob2FXWjBZWEJ3Y3k1agpiMjB3SGhjTk1qSXdNekl4TURrek16RXlXaGNOTWpNd05ESXdNRGt6TXpFeVdqQTJNVFF3TWdZRFZRUUREQ3NxCkxtRndjSE11WXkxeWFDMWpMV1Z3YUM0NGNEQmpMbkF4TG05d1pXNXphR2xtZEdGd2NITXVZMjl0TUNvd0JRWUQKSzJWd0F5RUFzaTU1UGVKQmllM3VvUUhRVVRQclNLSzdCZ2hHYm0zVTNnNlJUV2tKbE9xalV6QlJNQjBHQTFVZApEZ1FXQkJTOFMxbDF3NlhDV1poYlF1ZGRBQ240NDR1VVVEQWZCZ05WSFNNRUdEQVdnQlM4UzFsMXc2WENXWmhiClF1ZGRBQ240NDR1VVVEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BVUdBeXRsY0FOQkFNRnZMN1RSeC9LZGN0QUIKTFNOWklDTHZ3YlJrQ1BDR2JFbkZwcmNtcEs1RklHSWEwNXRCRTVKSVFhTDRQRmhFU2FDRFBWTHpTSWhFa1UvcQpQWDFuOHcwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJRRENCODZBREFnRUNBaFE3NzhOd0NOS3JTc1dZZUEraDN5aVV2cE1lMVRBRkJnTXJaWEF3RmpFVU1CSUcKQTFVRUF3d0xjbWhsYkMxelpYSjJaWEl3SGhjTk1qSXdNekl4TURrek16RXlXaGNOTWpNd05ESXdNRGt6TXpFeQpXakFXTVJRd0VnWURWUVFEREF0eWFHVnNMWE5sY25abGNqQXFNQVVHQXl0bGNBTWhBTmZqQW5URWRzRklLLzJhClU0elljaDRRclI1STN3Tk9aMVZERXh2QUxBWlNvMU13VVRBZEJnTlZIUTRFRmdRVWZYNy9OVzl4ck5hQkNRZ0UKWENabVdlTFhJRk13SHdZRFZSMGpCQmd3Rm9BVWZYNy9OVzl4ck5hQkNRZ0VYQ1ptV2VMWElGTXdEd1lEVlIwVApBUUgvQkFVd0F3RUIvekFGQmdNclpYQURRUURFaVdPUlFONmREcmR2VGc0ZWJUamk0QTdEYjFPb00ydUZaU2xmCldLZWIyZ2xjc2dPZ1dic1JMTXJKa0pXZFRPR0htRVpNVGdHK1pGWmdMZDZabW9ZQwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==

- kind: Pod
  apiVersion: v1
  metadata:
    name: cockpit-cloud-pod
    labels:
      infra: cockpit-cloud
  spec:
    containers:
      - name: cockpit-cloud
        image: quay.io/lis/cockpit-cloud
        ports:
          - name: session
            containerPort: 8080
          - name: cockpit
            containerPort: 9090
        volumeMounts:
          - name: secrets
            mountPath: /container/secrets
            readOnly: true
    volumes:
      - name: secrets
        secret:
          secretName: cockpit-cloud-pod-keys
    restartPolicy: Never

- kind: Service
  apiVersion: v1
  metadata:
    name: cockpit-cloud-service
  spec:
    ports:
    - name: session
      targetPort: 8080
      port: 8080
      protocol: TCP
    - name: cockpit
      targetPort: 9090
      port: 9090
      protocol: TCP
    selector:
      infra: cockpit-cloud

- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: cockpit-cloud-session
  spec:
    to:
      kind: Service
      name: cockpit-cloud-service
    port:
      targetPort: 8080
    tls:
      termination: passthrough

- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: cockpit-cloud-pod
  spec:
    to:
      kind: Service
      name: cockpit-cloud-service
    port:
      targetPort: 9090
    tls:
      termination: edge
